Simplify the Dockerfile

diff --git a/ci/release-tag b/ci/release-tag
--- a/ci/release-tag
+++ b/ci/release-tag
@@ -1,5 +1,11 @@
 #!/bin/bash -e
 
+if [ -z ${MAJOR_VERSION} ]
+then
+    echo "MAJOR_VERSION environment variable is required."
+    exit 2
+fi
+
 TAG=`git tag --list --points-at=HEAD`
 LAST_TAG=`git describe --abbrev=0 --tags`
 RELEASE_TAG=${MAJOR_VERSION}
